# 5 interesting PyTorch funtions

### An short introduction to 5 PyTorch functions. 
- `torch.eye()`
- `torch.chunk()`
- `torch.tile()`
- `torch.matrix_power()`
- `torch.Tensor.clone()`


In [81]:
# Import torch and other required modules
import torch
import numpy

## Function 1 - torch.eye()

> `torch.eye` returns a 2D tensor with the values of diagonals as 1 and other values as 0

In [19]:
# Example 1 - working 
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Here, `n=3` returns a ***3x3*** 2D tensor. If m is not specified, then it returns a 2D tensor of size ***nxn***.
And, the data type is `float` by default.

In [20]:
# Example 2 - working
torch.eye(5, 3, dtype=int)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 0, 0],
        [0, 0, 0]])

Here, `n=5` and `m=3` returns a 2D tensor of ***nxm*** and argument `dtype=int` used to specify the desired data type of returned tensor.
So, the returned tensor is of `int` data type.

In [18]:
# Example 3 - breaking (to illustrate when it breaks)
torch.eye(-1)

RuntimeError: ignored

`torch.eye` only accepts *positive* numbers.


This, function is very useful when we want to create a tensor with the diagonals having `1`*'s* and others having `0`*'s*.

Let's save our work using Jovian before continuing.

## Function 2 - torch.chunk()

> `torch.chunk(input, chunks, dim=0)` → List of Tensors

This function splits tensor into defined number of chunks, where 
- `input` - tensor which needs to be spitted, 
- `chunks` - number of chunks we need, 
- `dim` - dimension along which to split.

In [24]:
# Example 1 - working
input = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
output = torch.chunk(input, 5)
output

(tensor([1, 2]),
 tensor([3, 4]),
 tensor([5, 6]),
 tensor([7, 8]),
 tensor([ 9, 10]))

In this above example, we have an input tensor with 10 elements in it. Then, it is passed to `torch.chunk()` function with parameter `chunks=5` to split our tensor into 5 chunks.

In [28]:
# Example 2 - working
input = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
output = torch.chunk(input, 5, dim=1)
output

(tensor([[1],
         [6]]), tensor([[2],
         [7]]), tensor([[3],
         [8]]), tensor([[4],
         [9]]), tensor([[ 5],
         [10]]))

In this example we have spitted our tensor into **5** chunks with parameter `dim=0`, this parameter sets up the axis of our tensor to be spitted.

In [30]:
# Example 3 - breaking
input = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
output = torch.chunk(input, 5, dim=2)
output

IndexError: ignored

As we see function breaks and throws *Index Error* when *dim* parameter is set out of range which can be from *-2 to 1*.


The use of this function may be very helpful when we have large tensor and need to split it to smaller pieces.

## Function 3 - torch.tile()

> `torch.tile(input, reps)` → Tensor

Constructs a tensor by repeating the elements of input. 
The `reps` argument specifies the number of repetitions in each dimension.

In [49]:
# Example 1 - working
x = torch.tensor([1, 2, 3])
x.tile((2,))

tensor([1, 2, 3, 1, 2, 3])

Here, tensor `x` is defined and `.tile()` function is called with `reps=((2,))` for *2* repetitions of the tensor.

In [50]:
# Example 2 - working
y = torch.tensor([[1, 2], [3, 4]])
torch.tile(y, (2, 2))

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

In this example, tensor `y` is repetited *twice per dimension*. 

In [52]:
# Example 3 - breaking
x = torch.tensor([1, 2, 3])
x.tile((-1,))

RuntimeError: ignored

The code throws an error when we try to call the `tensor.tile()` with *negative values*.

The `tensor.tile()` function is useful when we want to repeat the elements of a tensor in a given number of repetitions per dimension.

## Function 4 - torch.matrix_power()

> `torch.matrix_power(input, n, *, out=None)` → Tensor

With this function we can raise matrix to power of `n`. If `n` is negative we receive reversed input matrix raised to power of `n`. 

**Parameters:** 
- `input` - matrix we need to raise to power of n 
- `n` — number to raise our matrix to.

In [54]:
# Example 1 - working
input = torch.randn(2, 2)
print(input)
torch.matrix_power(input, 2)

tensor([[-0.1368,  0.8134],
        [-0.2539,  2.1900]])


tensor([[-0.1878,  1.6700],
        [-0.5213,  4.5896]])

Here we have tensor as a matrix filled with random numbers and we raise our matrix to power of 2. As, a result we receive a new tensor as output matrix raised to a power of 2.

In [55]:
# Example 2 - working
input = torch.randn(2, 2)
print(input)
torch.matrix_power(input, -2)

tensor([[ 0.4939,  0.5167],
        [-2.2017,  0.7680]])


tensor([[-0.2380, -0.2834],
        [ 1.2073, -0.3884]])

In this example we have same situation except we have negative `n`. So, we receive reversed input matrix raised to power of 2.

In [56]:
# Example 3 - breaking
input = torch.randn(3, 2)
print(input)
torch.matrix_power(input, -2)

tensor([[-0.2963,  1.8110],
        [-0.5186,  0.7996],
        [-0.9266,  0.0424]])


RuntimeError: ignored

Here we receive a ***Runtime Error*** because our input matrix is not a square matrix where we have same number of rows and columns.

Raising matrices to a power of n is very useful sometimes and easy to implement with `torch.matrix_power()` function.

## Function 5 - torch.Tensor.clone()

> `Tensor.clone(*, memory_format=torch.preserve_format)` → Tensor

`torch.Tensor.clone()` returns a copy of the tensor with the same size and data type.

In [65]:
# Example 1 - working
a = torch.tensor([[1., 2.],
                  [3., 4.],
                  [5., 6.]])
b = a.clone()
print(f"b = {b}")
print(f"a = {a}")

b = tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
a = tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In this example, we can create a deepcopy of the tensor using `.clone` method.

In [66]:
# Example 2 - working
a = torch.tensor([[1., 2.],
                  [3., 4.],
                  [5., 6.]])
b = a.clone()
a[1, 0] = 9
print(f"b = {b}")
print(f"a = {a}")

b = tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
a = tensor([[1., 2.],
        [9., 4.],
        [5., 6.]])


Here, after cloning `a` to `b`, the element is the 2nd row 1st column of `a` is assigned to a new value which doesn't reflect in b.

In [ ]:
# Example 3 - breaking
a = torch.tensor([1, 2, 3])
a = a.numpy()
b = a.clone()
print(b)

`.clone()` function cannot be used with numpy array.

When we create a copy of the tensor using `x=y` , changing one variable also affects the other variable since it points to the same memory location. To avoid this, we can create a deepcopy of the tensor using `.clone()` method.

## Conclusion

In this notebook, we got insights on 5 useful functions of PyTorch library. These functions can be used for different variety of purposes and are way to ease for solving simple tasks of deep learning practitioners.

The functions covered in this notebook, 
- `torch.eye()`
- `torch.chunk()`
- `torch.tile()`
- `torch.matrix_power()`
- `torch.Tensor.clone()`

## Reference Links

>* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
>* Great article on Towards data science: https://towardsdatascience.com/useful-pytorch-functions-356de5f31a1e
>* A great documentation: https://www.kite.com/python/docs